name: unit-test
on: [push, pull_request]
jobs:
  check-path-decomposition:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: lukka/get-cmake@latest
      - run: wget https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.gz
      - run: tar -xf boost_1_76_0.tar.gz
      - run: pwd
      - run: ls
      - run: git submodule update --checkout --force tdlib
      - uses: lukka/run-cmake@v3.4
      - run: ./ test
