name: unit-test
on: [push]
jobs:
  check-path-decomposition:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: lukka/get-cmake@latest
      - uses: lukka/run-cmake@latest
      - run: ./ test
